### ISSUE TITLE
Does not start on Wayland anymore

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.texstudio.TeXstudio#11]
After the last update, Texstudio does not start on Wayland anymore, although on X everything runs just fine.

[mzimmermann@mnb ~]$ flatpak run org.texstudio.TeXstudio
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.

[mzimmermann@mnb ~]$ flatpak info org.texstudio.TeXstudio 
Ref: app/org.texstudio.TeXstudio/x86_64/stable
ID: org.texstudio.TeXstudio
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-09-23 14:43:22 +0000
Subject: Use KDE Sdk 5.11 (1c2a8cfc)
Commit: 21c2629777a20e290e0bb1a77a1f9a093c75f077ce49ba0cf530442790bb4d2b
Parent: 252afa154e6572c6be5af3b0266e58a1588e74f0ed081d8397870405494f5c9b
Location: /var/lib/flatpak/app/org.texstudio.TeXstudio/x86_64/stable/21c2629777a20e290e0bb1a77a1f9a093c75f077ce49ba0cf530442790bb4d2b
Installed size: 3.2 GB
Runtime: org.kde.Platform/x86_64/5.11
Sdk: org.kde.Sdk/x86_64/5.11

**Comment by mczimmermann** [comment]
It starts, but it looks horrible (scaling wrong, title bar is blue?, ...)

[mzimmermann@mnb ~]$ QT_QPA_PLATFORM=wayland flatpak run org.texstudio.TeXstudio
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Using Wayland-EGL
Using the 'xdg-shell-v6' shell integration
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

**Comment by Alexander-Wilms** [comment]
Do other applications using Qt 5.11 (e.g. org.qgis.qgis) behave the same? If so, it might be an issue with the runtime or Gnome.

**Comment by mczimmermann** [comment]
I have checked Octave and DolphinEmu, which both should use 5.11

Both run without any issues, here are the outputs

[mzimmermann@mnb ~]$ flatpak run org.octave.Octave --gui

[mzimmermann@mnb ~]$ flatpak run org.DolphinEmu.dolphin-emu 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

**Comment by Alexander-Wilms** [comment]
Hm, that's pretty strange. I wonder why Dolphin doesn't show this part of the rror message anymore:
```
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```
@aleixpol Do you have some insight?

**Comment by mczimmermann** [comment]
I am confused, I thought if a Gnome session runs on Wayland then XDG_SESSION_TYPE is wayland? Can I provide any other information that could help?

**Comment by koenigjaeger** [comment]
Just wanted to report I am having the same issue on Fedora Silverblue 28 using wayland. 

Error:
```
flatpak run org.texstudio.TeXstudio 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

**Comment by Alexander-Wilms** [comment]
I'll install Gnome and see if I can find a way to fix this.

**Comment by Alexander-Wilms** [comment]
I can reproduce this. Relating to this issue, I found https://unix.stackexchange.com/questions/450411/qt5-font-size-too-big-when-run-in-gnome-on-wayland and https://bugreports.qt.io/browse/QTBUG-68619

Maybe simply recompiling TeXstudio helps, that's what I'll try first.

**Comment by Alexander-Wilms** [comment]
I've removed the Wayland permission for now. It works fine with XWayland.

**Comment by mczimmermann** [comment]
Works for me again in Wayland session. Many thanks!
