### ISSUE TITLE
Cannot open TeX files from my file manager

### ISSUE THREAD

**Issue by Zishan-Rahman** [flathub/org.texstudio.TeXstudio#117]
Hi, all!

Recently, I've started having this issue when I try to open a TeX file from Nemo (I'm using Linux Mint 21):

https://user-images.githubusercontent.com/45298929/198898484-6e70e252-cc16-4745-ae50-dfefee2db068.mp4

Opening TeX files from TeXStudio itself works just fine, by the way.

Still, I don't know why this is happening or what might've caused it, but I'd very much appreciate it if this could get looked into.

Thanks in advance, and, also, thanks for maintaining this Flatpak!

**Comment by Alexander-Wilms** [comment]
That appears to be caused by the switch launching TeXstudio via script to set the perl version.

Can you try this build?

https://github.com/flathub/org.texstudio.TeXstudio/pull/118

**Comment by Alexander-Wilms** [comment]
No problem
