### ISSUE TITLE
Should be updated from 4.2.3 -> 4.3.1

### ISSUE THREAD

**Issue by applecuckoo** [flathub/org.texstudio.TeXstudio#120]
4.3.1 was released back in August.

**Comment by jakobjakobson13** [comment]
Texstudio was already updated in 632b42e498ab92b3f9233e06c97429edc68997c5 to version 4.3.1.

**Comment by applecuckoo** [comment]
That's odd, Linux Mint Software manager seems to say 4.2.3.
