### ISSUE TITLE
flatpak run --command=mktexlsr can't write to /app/texmf*

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.texstudio.TeXstudio#13]
Hello, I'm trying to include a new template to TeXstudio and according to the installations instructions you need to run `mktexlsr` after putting it to `~/texmf`.

So I tried `flatpak run --command=mktexlsr org.texstudio.TeXstudio/x86_64/stable` and got this:
```
mktexlsr: /app/texmf-config: directory not writable. Skipping...
mktexlsr: /app/texmf-dist: directory not writable. Skipping...
mktexlsr: /app/texmf-local: directory not writable. Skipping...
mktexlsr: /app/texmf-var: directory not writable. Skipping...
mktexlsr: Done.
```

**Comment by Alexander-Wilms** [comment]
Hm, not sure how to easily work around this. /app is supposed to be read-only. Maybe you could call mktexlsr outside the sandbox, but that would defeat the purpose of having TeX Live bundled.

**Comment by Zlopez** [comment]
@Alexander-Wilms 
I tried that, but the TeXstudio still can't find the template.

**Comment by Alexander-Wilms** [comment]
Die you successfully run mktexlsr with the path top the flatpakd TeX Live or did that command fail already?

An alternative you can try is adding `flatpak-spawn --host` in front of all the commands used by TeXstudio and just use the TeX Live Version installed on your host.

**Comment by Zlopez** [comment]
I executed `mktexlsr` system wide, hoped that the config folders are the same. If not than I didn't run it successfully in flatpak. :-(

**Comment by Alexander-Wilms** [comment]
No, the config folders are under `~/.local/share/flatpak/app/org.texstudio.TeXstudio/x86_64/stable/active/files/` or `/var/lib/flatpak/app/org.texstudio.TeXstudio/x86_64/stable/active/files/`

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation. Thus, this issue should no longer occur.
