### ISSUE TITLE
TexStudio does not find flathub TexLive SDK and/or Perl

### ISSUE THREAD

**Issue by PunkPangolin** [flathub/org.texstudio.TeXstudio#138]
I have a problem which must be something to do with TexStudio, because in VSCodium everything works fine with the latex-workshop extension. When I try to compile a file, I get the following error message (translated by me):

```
process started: flatpak-spawn --host biber "main"

Portal call failed: Failed to start command: child process »biber« could not get executed (file or directory not found)
Process ended with error(s)

Process started: flatpak-spawn --host xelatex -synctex=1 -interaction=nonstopmode "main".tex

Portal call failed: Failed to start command: child process »xelatex« could not get executed (file or directory not found)
Process ended with error(s)
```

After removing "--host" from the "Commands" page in the preferences, TexStudio finds biber and XeLaTeX, but not perl.

```
Process started: flatpak-spawn biber "main"

perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
Process ended with error(s)
```

**Comment by Alexander-Wilms** [comment]
Strange, when I run the command in [texstudio.sh](https://github.com/flathub/org.texstudio.TeXstudio/blob/master/texstudio.sh) manually, it works:

```
alexander@PC:~> flatpak run --command=sh org.texstudio.TeXstudio 
[📦 org.texstudio.TeXstudio ~]$ biber
perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
[📦 org.texstudio.TeXstudio ~]$  if [ -d /app/texlive ]
 then
     cd /app/texlive/lib/perl5/site_perl/
     perl_version=$(ls)
     # add paths of TeXlive Flatpak extension binaries
     export PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
     # add include paths for Perl @INC variable
     export PERL5LIB=/app/texlive/lib/perl5/site_perl/$perl_version/:/app/texlive/lib/perl5/$perl_version/
     # add library paths
     export LD_LIBRARY_PATH=/app/texlive/lib/:/app/texlive/lib/perl5/$perl_version/x86_64-linux/CORE/:/app/texlive/lib/perl5/$perl_version/aarch64-linux/CORE/
 fi
[📦 org.texstudio.TeXstudio site_perl]$ biber
Usage:
      biber [options] file[.bcf]
      biber [options] --tool <datasource>

      Creates "file.bbl" using control file "file.bcf" (".bcf" extension is
      optional). Normally use with biblatex requires no options as they are
      all set in biblatex and passed via the ".bcf" file

      In "tool" mode (see B<--tool> option), takes a datasource (defaults to
      "bibtex" datasource) and outputs a copy of the datasource with any command-line
      or config file options applied.

      Please run "biber --help" for option details
```

**Comment by Alexander-Wilms** [comment]
Can you try if https://github.com/flathub/org.texstudio.TeXstudio/pull/139 fixes this for you as well?

**Comment by PunkPangolin** [comment]
No, unfortunately not, I get exactly the same error.

**Comment by Alexander-Wilms** [comment]
Hm, do you get the same output when you follow the steps in the cnippet above?

**Comment by pr0ton11** [comment]
I have the same issue on Fedora Silverblue, allthough for me, none of the commands work.
Is it expected to have a flatpak that relies on the host to have these tools installed? If I am looking in the patch that changes the commands, it seems to be the case.

**Comment by PunkPangolin** [comment]
I tried TeXstudio, TeXworks, Gummi, Setzer and VSCodium with the latex-workshop extension. Only VSCodium was able to compile the file, perhaps because it uses latexmk. TeXworks, Gummi and Setzer told me to run biber again, but they did not seem to find it. To get TeXstudio to do anything at all, I had to remove "--host" from the commands on the preferences page. After that, it could not find perl and therefore could not run biber.

**Comment by jakobjakobson13** [comment]
Could you try the following command?
```
flatpak run --command=sh --env=PATH=/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux:/app/texlive/bin:/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/texlive/lib/perl5/5.38.0/x86_64-linux/CORE org.tug.texworks
```

The background is that the `perl` and `biber` commands are located in `/app/texlive/bin` which has not been included in the paths yet and the `libperl.so` required by `perl` is located in the library path ` /app/texlive/lib/perl5/5.38.0/x86_64-linux/CORE`.

**Comment by jakobjakobson13** [comment]
Could someone do me a favour and run the file given below (for instructions see https://github.com/flatpak/flatpak-builder-tools/tree/master/cpan) on the biber archive (https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/biblatex-biber.tar.gz/download)

[flatpak-cpan-generator.txt](https://github.com/flathub/org.texstudio.TeXstudio/files/12088886/flatpak-cpan-generator.txt)

I'm using openSUSE leap and its perl is to old to run the script.

**Comment by PunkPangolin** [comment]
> Could you try the following command?
> [...]
> Now, I guess that the biber dependencies are broken and have to be updated.

I get the exact same error, you are probably right about that.

> Could someone do me a favour and run the file given below (for instructions see https://github.com/flatpak/flatpak-builder-tools/tree/master/cpan) on the biber archive (https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/biblatex-biber.tar.gz/download)

The script worked for me, but just in a toolbox. But that should not matter, hopefully: [generated-sources.tar.gz](https://github.com/flathub/org.texstudio.TeXstudio/files/12135100/generated-sources.tar.gz)

**Comment by jakobjakobson13** [comment]
I updated the biber dependencies but could not check it so far. Could you try one the editors again with the parameters given above after updating the texlive extension?

**Comment by PunkPangolin** [comment]
Unfortunately, the update did not change anything on my side, even the Texworks error remains exactly the same.

**Comment by jakobjakobson13** [comment]
> Unfortunately, the update did not change anything on my side, even the Texworks error remains exactly the same.

Okay, let´s go to the next round. The following options resulted in a successful compilation of a bibliography (with the biber backend):

`flatpak run --command=sh --env=PATH=/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux:/app/texlive/bin:/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/texlive/lib:/app/texlive/lib/perl5/5.38.0/x86_64-linux/CORE --env=PERL5LIB=/app/texlive/lib/perl5/5.38.0:/app/texlive/lib/perl5/site_perl/5.38.0 org.tug.texworks`

**Comment by PunkPangolin** [comment]
> > Unfortunately, the update did not change anything on my side, even the Texworks error remains exactly the same.
> 
> Okay, let´s go to the next round. The following options resulted in a successful compilation of a bibliography (with the biber backend):
> 
> `flatpak run --command=sh --env=PATH=/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux:/app/texlive/bin:/app/bin:/usr/bin --env=LD_LIBRARY_PATH=/app/texlive/lib:/app/texlive/lib/perl5/5.38.0/x86_64-linux/CORE --env=PERL5LIB=/app/texlive/lib/perl5/5.38.0:/app/texlive/lib/perl5/site_perl/5.38.0 org.tug.texworks`

Aye, it works for me too! I also tried adding these parameters to TeXstudio and it worked perfectly, both in shell and GUI. Thanks for solving this!

**Comment by Alexander-Wilms** [comment]
Does this version work for you as well?

https://github.com/flathub/org.texstudio.TeXstudio/pull/137

**Comment by PunkPangolin** [comment]
It works now, thank you very much! However, I had to recommend "flatpak-spawn --host" in the settings for the commands to work.
