### ISSUE TITLE
Texstudio does not start anymore

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.texstudio.TeXstudio#14]
Same as #11, but I don't know how to reopen the old issue.

Using Fedora Silverblue 29.20190212.0 and GNOME on Wayland, 
after today's update, Texstudio is again not starting 

$ flatpak run org.texstudio.TeXstudio 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb. 

I tested it also under X11, where I got the same error.

**Comment by Alexander-Wilms** [comment]
Oh, I thought the Qt bug would be resolved in version 5.12. I've removed the Wayland permission, so it should work again now.

**Comment by mczimmermann** [comment]
Thanks for the quick fix! Just wanted to confirm that it is working again for me.
