### ISSUE TITLE
Really slow download

### ISSUE THREAD

**Issue by pgera** [flathub/org.texstudio.TeXstudio#16]
```
org.texstudio.TeXstudio permissions:
    ipc     network     fallback-x11     x11     dri     file access [1]     dbus access [2]

    [1] host, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
    [2] com.canonical.AppMenu.Registrar, com.canonical.AppMenu.Registrar.*


        ID                              Arch           Branch         Op         Remote         Download
 1. [✓] org.kde.Platform                x86_64         5.12           u          flathub        622.4 kB / 485.1 MB
 2. [✓] org.kde.Platform.Locale         x86_64         5.12           u          flathub          1.0 kB / 236.8 MB
 3. [\] org.texstudio.TeXstudio         x86_64         stable         i          flathub          6.3 MB / 1.5 GB

Installing 3/3… ██▏                   11%  47.6 kB/s
```

Why is it so big and so slow ? I am on a gigabit connection.

**Comment by Alexander-Wilms** [comment]
The size is due to the entirety of TeXLive being bundled. The slow download speed should be reported at https://github.com/flathub/flathub

**Comment by pgera** [comment]
Can texlive be a separate flatpak ? This is rather wasteful to get GBs of data to get an editor.

**Comment by Alexander-Wilms** [comment]
I could try to put it into an optional extension of the TeXstudio flatpak instead and change the commands to use flatpak-spawn.

**Comment by pgera** [comment]
I'm not too familiar with flatpak or texstudio, but does that allow choosing between system binaries for texlive and the flatpak extension for texlive ? If yes, that definitely sounds like a better solution. How is the $PATH exposed to texstudio flatpak ? I don't see any configuration parameter in the texlive GUI for $PATH other than the individual commands under options -> config -> commands.

**Comment by willsALMANJ** [comment]
The slow download is not really this flatpak's fault, but I think it would be good to find a way to help with it if possible. I have tried installing the flatpak a few times on different internet connections and it has timed out after downloading around 1 GB each time. Is there any way to split it into logical chunks like the freedestkop, KDE, and GNOME platform flatpaks are split out that could break it up into reasonably sized components?
