### ISSUE TITLE
bwrap: Can't make symlink at /var/run: File exists

### ISSUE THREAD

**Issue by Camiropan** [flathub/org.texstudio.TeXstudio#164]
Since the update today i can't start TeXstudio anymore.

### Step to reproduce
update TeXstudio
start TeXstudio (flatpak run org.texstudio.TeXstudio)
get the error message: "bwrap: Can't make symlink at /var/run: File exists"

### Versions
Flatpak 1.15.4
fedora 38

i tried to set the filesystem-permissions to "--filesystem=host" via flatseal. Unfortunately that does not help.
Since the Octave flatpak got the same commits today there exists this issue also.

**Comment by Alexander-Wilms** [comment]
Can you test if https://github.com/flathub/org.texstudio.TeXstudio/pull/165 fixes this once the build is done?

**Comment by Camiropan** [comment]
Yes, i tried it and the issue is still there.
I also did a fresh install of the flatpak in a GnomeOS VM and tried the command but the issue still exists.
However, when i reinstall it from the test repo (so "flatpak uninstall --delete-data org.texstudio.TeXstudio" and "flatpak install --user https://dl.flathub.org/build-repo/44723/org.texstudio.TeXstudio.flatpakref") it works.

**Comment by Camiropan** [comment]
Very nice. Thanks again and thanks also for your job as a flatpak-maintainer :D.
