### ISSUE TITLE
Tighten permissions

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.texstudio.TeXstudio#169]
This was added in https://github.com/flathub/org.texstudio.TeXstudio/commit/dfc578349655636053f23f39c7b49f1c3d92705e but Texstudio no longer uses host's Texlive and giving access to `/tmp` is not desirable.

- Can this be dropped?
- Can this be changed by setting the TMPDIR variable to $XDG_CACHE_HOME inside the sanbox, if it is still required?

**Comment by bbhtt** [comment]
org.freedesktop.Flatpak is essentially a sandbox escape, it allows any command to be run on host, nullifying the effectiveness of the flatpak's sandboxing

I see the reason to do that was support distro's texlive https://github.com/flathub/org.texstudio.TeXstudio/issues/161, but that doesn't seem right reason, those wanting to do that can manually configure it. The default should be secure and people expect to download the TexLive extension and the reason for it to exist.

**Comment by Alexander-Wilms** [comment]
I'd prefer to keep the option for both ways of using TeX Live.

The TeX Live Flatpak did have issues in the past that resulted in not every LaTeX use case being supported. E.g. calling tools like Inkscape or more niche ones during compilation.

And while Flatpak's sandbox is nice, I think having a working TeX editor for a wider audience is more useful, so I'm more interested in Flatpak allowing an up-to-date TeX editor to be used.

It's not more insecure than the TeXstudio distro packages and Flathub as well as Gnome Software do show a warning.

**Comment by bbhtt** [comment]
> I'd prefer to keep the option for both ways of using TeX Live.

You can just keep the flatpak-wrapper installed and not replace the commands, and make the Texlive SDK autodownload which is what other LatTex editors do.

What I'm saying is not to make it a default, those who want to use distro's tex distribution or external tools can do it so by giving the permission via flatpak override or Flatseal GUI.

> having a working TeX editor for a wider audience is more useful

I checked with the extension and most compile commands should work out of the box with like it does on others like Texmaker (Which doesn't do this)


> It's not more insecure than the TeXstudio distro packages

You made it the same as distro packages, what's he point in flatpaking it if not trying to benefit from the sandbox...

**Comment by Alexander-Wilms** [comment]
Closing, since it would reduce usability.
