### ISSUE TITLE
FD 23.08

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/org.texstudio.TeXstudio#170]
Can the flatpak be updated to use the new FD version?

**Comment by Alexander-Wilms** [comment]
Requires a new KDE runtime on top of FDO 23.08

Cf. #172

**Comment by jakobjakobson13** [comment]
> Requires a new KDE runtime on top of FDO 23.08

They should be available, see https://github.com/flathub/buildbot-config/pull/87 and https://github.com/flathub/buildbot-config/pull/88.

**Comment by Alexander-Wilms** [comment]
The buuildbot still shows this error message:

` Could not find requested SDK org.kde.Sdk//6.6`

**Comment by Alexander-Wilms** [comment]
There's some bug causing the KDE SDK build to fail, the maintainers are already aware.

**Comment by bbhtt** [comment]
6.6 is now available on Flathub

**Comment by Alexander-Wilms** [comment]
The build can be tested.
