### ISSUE TITLE
Error: Could not start the command: pdflatex

### ISSUE THREAD

**Issue by mpanhans** [flathub/org.texstudio.TeXstudio#172]
One week ago compiling worked fine. I noticed some recent updates, and today I receive the following when trying to compile the same document through TexStudio:
Error: Could not start the command: pdflatex -synctex=1 -interaction=nonstopmode "filename".tex

**Comment by Zishan-Rahman** [comment]
The most recent update was for updating the Freedesktop runtime from which the texlive extension is sourced. You'll have to install the new 23.08 runtime's branch of the texlive extension like so:
```
flatpak install flathub org.freedesktop.Sdk.Extension.texlive//23.08
``` 
After that, reopen TeXstudio and then you should be able to compile documents as before.

If no other applications on your system are using the 22.08 branch of this extension, you can uninstall it:
```
flatpak remove org.freedesktop.Sdk.Extension.texlive//22.08
```
You can alternatively use `flatpak remove --unused` to remove any unused runtimes and extensions from your system.

**Comment by mpanhans** [comment]
Thanks for the quick response.  I installed texlive extension 23.08 and am getting a new error:

/app/texlive/bin/x86_64-linux/pdflatex: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /app/texlive/bin/x86_64-linux/pdflatex)

**Comment by CaKrome** [comment]
I have the same issue with 23.08 branch of `org.freedesktop.Sdk.Extension.texlive`

``pdflatex: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by pdflatex)``

**Comment by jakobjakobson13** [comment]
You are right, pdflatex/xelatex/lualatex are not working.

I´m not sure about the reason but that´s what I found so far:
- texworks and texmaker are using the texlive 22.08 extension and are working
- texstudio uses the texlive 23.08 extension and is not working

I found a [bug](https://github.com/flathub/com.github.xournalpp.xournalpp/pull/86) describing the same issue stating it is due "outdated" gnome extension. [Qt6.5](https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/qt6.5/org.kde.Sdk.json.in?ref_type=heads) is based on the freedesktop extension 22.08 and therefore does not ship GLIB_2.38 which was released after the release of the freedesktop extension 22.08. So by following this argumentation you either have to
- wait for the QT6.6 extension (which I did not find (yet?) in the kde repository)
- switch to qt5.15-23.08 (which is in the kde repository but I could not find any announcement and none of the kde apps is using it, so it might not be released yet)
This in agreement with the `libc.so.6` libraries in all three editors being built with GNU libc 2.35.

So as long as the kde extension is not updated, I see no other way than downgrading the texlive extension again till the release of a newer kde extension.

**Comment by Zishan-Rahman** [comment]
> So as long as the kde extension is not updated, I see no other way than downgrading the texlive extension again till the release of a newer kde extension.

I opened a PR to action this downgrade: flathub/org.texstudio.TeXstudio#174

**Comment by Zishan-Rahman** [comment]
When I initially tested the runtime upgrade on my own computer, TeXstudio was working for me, so I was a bit confused about the aforementioned problems mentioned here after installing the extension. I had no idea there were these issues with the runtime itself, as @jakobjakobson13 described [in his comment](https://github.com/flathub/org.texstudio.TeXstudio/issues/172#issuecomment-1762037519) (sorry for the ping). I should've done my research here and actually looked into what these runtimes actually rely on behind the scenes, to ensure the upgrade was actually ready to be actioned, but what's happened has happened. Even then, this was a stupid mistake on my end and I'm sorry for causing all this trouble. As I mentioned already, I opened the PR #174 to reverse this mistake and make up for it.

If anyone wants to install [the test build with the downgraded runtime](https://github.com/flathub/org.texstudio.TeXstudio/pull/174#issuecomment-1762072442) before it gets pushed to Flathub:
```
flatpak install --user https://dl.flathub.org/build-repo/56058/org.texstudio.TeXstudio.flatpakref
```

**Comment by mpanhans** [comment]
No worries. The test build with downgraded runtime is working for me. Thanks, I'll close this issue.

**Comment by Doomsdayrs** [comment]
Should #170 be reopened with this additional context? 

Since eventually an update should be made.

**Comment by Zishan-Rahman** [comment]
> Should #170 be reopened with this additional context?
> 
> Since eventually an update should be made.

I agree that it should. That way, anyone seeing it will know _why_ an extension update can't be (and shouldn't've been) actioned just yet.
