### ISSUE TITLE
Odd (missing?) window decorations

### ISSUE THREAD

**Issue by JNKL** [flathub/org.texstudio.TeXstudio#180]
Window decorations are missing (see screenshot) and double click on title bar to maximize window does not work.

![Bildschirmfoto vom 2023-12-06 17-52-04](https://github.com/flathub/org.texstudio.TeXstudio/assets/10925420/def9df75-ba90-4a02-a790-61838e166308)

**Comment by Alexander-Wilms** [comment]
Can you test if you encounter the same issue with https://flathub.org/apps/page.codeberg.JakobDev.jdDiff ?

I assume it's related to Qt 6.

And could you try a Qt 6 application from your distro's repository?

**Comment by JNKL** [comment]
jdDiff has the same problem on a default setup Debian stable (Gnome Shell), german language.

**Comment by Alexander-Wilms** [comment]
Then you should probably report this issue against the KDE Flatpak runtime and/or Gnome.

**Comment by JNKL** [comment]
Against which repository?

**Comment by Alexander-Wilms** [comment]
https://bugs.kde.org/enter_bug.cgi?product=Qt%2FKDE%20Flatpak%20Runtime

and maybe

https://gitlab.gnome.org/GNOME/gnome-shell

**Comment by Alexander-Wilms** [comment]
Anyway, I don't think this could be fixed in the package.
