### ISSUE TITLE
yaml hard coded x86_64

### ISSUE THREAD

**Issue by cheese** [flathub/org.texstudio.TeXstudio#19]
```
 - --env=PATH=/usr/bin:/app/bin:/app/bin/x86_64-linux
```

**Comment by jakobjakobson13** [comment]
> ```
>  - --env=PATH=/usr/bin:/app/bin:/app/bin/x86_64-linux
> ```

This is not a bug as the texlive binaries are in the directory `/app/bin/x86_64-linux`.

**Comment by cheese** [comment]
This is not an issue since this package supports only x86_64. But this may break if this package is going to support other architecture.

**Comment by jakobjakobson13** [comment]
> This is not an issue since this package supports only x86_64. But this may break if this package is going to support other architecture.

In that case the manifest has to be updated, yes. But currently texlive is build from a downloaded iso and the supported architectures of the iso are very limited as the 386 and arm architectures are not supported.

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation and doesn't hardcode the PATH variable.
