### ISSUE TITLE
Doesn't show up on flathub.org

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.texstudio.TeXstudio#2]
@jgarciao The icon doesn't show up on KDE, could this be the cause? Cf. https://github.com/texstudio-org/texstudio/issues/88

**Comment by TingPing** [comment]
>  <launchable type="desktop-id">texstudio.desktop</launchable>

I don't think that is handled automatically with renaming.

**Comment by Alexander-Wilms** [comment]
It does export an icon, though:

```
Exporting share/applications/org.texstudio.TeXstudio.desktop
Exporting share/icons/hicolor/scalable/apps/org.texstudio.TeXstudio.svg
```

When installing it, the icon shows up under /var/lib/flatpak/apps/icons/hicolor/scalable/apps/org.texstudio.TeXstudio.svg, but the .desktop launcher still uses a generic fallback icon.

I'll try renaming the launchable-entry manually and see if that fixes it.

**Comment by Alexander-Wilms** [comment]
Changing the launchable entry fixed it. Should I open an issue regarding thus in flatpak/flatpak?

**Comment by TingPing** [comment]
Against flatpak/flatpak-builder
