### ISSUE TITLE
Texstudio ships with an outdated version of the package chngctr.sty

### ISSUE THREAD

**Issue by Ethunxxx** [flathub/org.texstudio.TeXstudio#21]
The Texstudio flatpak ships with chngctr.sty version 1.0. This caused an error when I tried to compile my Latex document (the same as in this [question](https://tex.stackexchange.com/questions/425600/latex-error-command-counterwithout-already-defined)). The newest version of this package is 1.1.

**Comment by jakobjakobson13** [comment]
See [here](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/9) and [here](https://github.com/flathub/org.texstudio.TeXstudio/issues/33) for a similar problem.

**Comment by jakobjakobson13** [comment]
@Ethunxxx Could you check if the latest update solves your problem?

**Comment by Ethunxxx** [comment]
> @Ethunxxx Could you check if the latest update solves your problem?

@jakobjakobson13 I'd like to help, but the [version available on Flathub](https://flathub.org/apps/details/org.texstudio.TeXstudio) is still from April 7, 2019. Where can I find the latest update?

**Comment by jakobjakobson13** [comment]
> > @Ethunxxx Could you check if the latest update solves your problem?
> 
> @jakobjakobson13 I'd like to help, but the [version available on Flathub](https://flathub.org/apps/details/org.texstudio.TeXstudio) is still from April 7, 2019. Where can I find the latest update?

Apparently the flathub package did not get updated. The lastest build is roughly a week old and should have the the revision d4e27005d20889aa738da129ea6b6b0e5c0a0528.

**Comment by Ethunxxx** [comment]
> > > @Ethunxxx Could you check if the latest update solves your problem?
> > 
> > 
> > @jakobjakobson13 I'd like to help, but the [version available on Flathub](https://flathub.org/apps/details/org.texstudio.TeXstudio) is still from April 7, 2019. Where can I find the latest update?
> 
> Apparently the flathub page did not get updated. The lastest build is roughly a week old and should have the the revision [d4e2700](https://github.com/flathub/org.texstudio.TeXstudio/commit/d4e27005d20889aa738da129ea6b6b0e5c0a0528).

Ok, where can I find build instructions?

**Comment by jakobjakobson13** [comment]
If you already installed it, you can update it by `flatpak update`. To build it locally you have to download the manifest and use the `flatpak-builder`.

**Comment by Ethunxxx** [comment]
> If you already installed it, you can update it by `flatpak update`. To build it locally you have to download the manifest and use the `flatpak-builder`.

@jakobjakobson13 I installed the latest version from Flathub and I don't get errors any more. Hence, I believe this issue was resolved and can be closed. Thanks for your work!
