### ISSUE TITLE
Documents opened from file manager launch separate instances of TeXStudio

### ISSUE THREAD

**Issue by cjao** [flathub/org.texstudio.TeXstudio#22]
If TeXStudio is already running and I open a tex file from Nautilus, I would expect it to open in the existing instance of TeXstudio. This is the behavior for TeXstudio installed from the usual package repositories. Instead, a separate instance of TeXstudio is started. The problem results from the flatpak version of TeXstudio storing its lockfiles in the wrong directory, and is rectified by pull request https://github.com/flathub/org.texstudio.TeXstudio/pull/18.

**Comment by Alexander-Wilms** [comment]
Should be fixed, since your change is now merged
