### ISSUE TITLE
Using epstopdf causes perl error

### ISSUE THREAD

**Issue by will-jj** [flathub/org.texstudio.TeXstudio#28]
When including an .eps image the following message is produced:
```
perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory

system returned with code 32512

Process exited with error(s)
```
The end result being image-eps-converted-to.pdf not found

**Comment by SuborbitalPigeon** [comment]
This appears to be https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/2

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation. Thus, this issue should no longer occur.
