### ISSUE TITLE
Package `svg` not working due to missing Inkscape

### ISSUE THREAD

**Issue by christiandreher** [flathub/org.texstudio.TeXstudio#29]
So I heavily use the `svg` package which depends on Inkscape to render a `svg` as `pdf` to include it.

I also use Inkscape from flathub, but this doesn't work together. The `svg` package uses `--shell-escape` to call Inkscape from the terminal.

What could be done to make this work with the flatpak versions of Inkscape and TeXstudio, if it is even possible?

**Comment by Alexander-Wilms** [comment]
One could patch the svg package to call Inkscape via flatpak-spawn --host.

**Comment by christiandreher** [comment]
I doubt that they would accept such a patch, right? I mean, this would break the package for every non-flatpak user

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation. If you have regular Inkscape installed, it works. For it to use flatpak'd Inkscape, the svg package would need to be patched to try running `flatpak run org.inkscape.Inkscape`.

**Comment by renanwp2** [comment]
Here, it does not use my Inkscape installed in my machine. I use Debian and the command that I use to compile is 

> pdflatex -shell-escape -synctex=1 -interaction=nonstopmode %.tex,

which is configured in the commands tab

**Comment by andersonjwan** [comment]
Have we found a solution to this? I am also facing this issue, and it seems the only temporary option I've found is to create a shell script by the name `inkscape` that is stored under a directory on the `PATH` with the following contents:

```bash
#!/usr/bin/bash

flatpak run org.inkscape.Inkscape "$@"
```

This works if you use the `pdflatex` command directly from the shell. However, I am using the `auctex` package for Emacs, and it does not accept this workaround---receiving the same error as https://github.com/flathub/org.texstudio.TeXstudio/issues/29#issue-488666395.
