### ISSUE TITLE
Add hidden directory to TeXlive search paths

### ISSUE THREAD

**Issue by christiandreher** [flathub/org.texstudio.TeXstudio#30]
I'd like to use custom packages, but I really hate having my home directory cluttered with folders from various programs etc.

In #7, you added support for the `$HOME/texmf` folder. I'd like to ask if you could add a hidden folder as well, like `$HOME/.texmf`, or even better, `$XDG_DATA_HOME/texmf` (`$HOME/.local/share/texmf`)

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation, so you can just set the regular TEXINPUTS environment variable to whatever you want.
