### ISSUE TITLE
Understanding tex distribution

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#31]
Sorry, for asking this here, but I am curious.

Here:

https://github.com/flathub/org.texstudio.TeXstudio/blob/ffaf1a13991ac5fa3b90597028a0df63bd863e3a/org.texstudio.TeXstudio.yaml#L6

you AFAIK (no flatpak package knowledge here) add a dependency on texlive here, so we can get all these tex packages, don't you?

Now I have a problem, because when I enter `flatpak info org.freedesktop.Sdk.Extension.texlive` I get no result. So I doubt this is installed on my system? Can this be true?

TeXStudio is installed and works on my system. `flatpak info org.texstudio.TeXstudio` works and only shows a kde platform and ask in there.

---

I want to know this, because I want to report an issue for a tex package in this flatpak… :thinking:

**Comment by Alexander-Wilms** [comment]
The issue seems to be solved
