### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#32]
There are two problems:
1. the application is always in English
2. but what may be the bigger problem: the synonym (thesaurus) feature is always in English

AFAIK you can put languages in an extra module, if that would otherwise result in a too big package.

FYI, for some reason, spellchecking already works in German here… :thinking:

**Comment by jakobjakobson13** [comment]
Actually, in the following directory `/var/lib/flatpak/app/org.texstudio.TeXstudio/x86_64/stable/5bbbc114485cb314b75f14eb3deea3b16448b782ab4350e0a250e14a6852f07b/files/share/texstudio` the german thesaurus is already there `th_de_DE_v2.dat`. And you can select him under "Language checking" -> "Thesaurus Database".

But I agree on you that you should neither have to switch the application language nor a thesaurus by hand to German if your system is set to German.

**Comment by rugk** [comment]
Hmm, if not installed as a flatpak it also automatically selects the correct version. So this has to be some bug here… :thinking:

**Comment by jakobjakobson13** [comment]
I would wait for another opinion from the texstudio deelopers before blaming flatpak. Also the locales within the flatpak package 
```bash
LANG=de_DE.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```
and my "normal" locales
```bash
LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```
differ substantialy. Perhaps, this could be due the line `- --env=LC_ALL=C` ?

**Comment by jakobjakobson13** [comment]
@rugk Can you try the command `flatpak override --env=LC_ALL= org.texstudio.TeXstudio` on your system? This should have the same effect as deleting the file of `- --env=LC_ALL=C # works around LuaLaTex issue with locale` in the manifest file. This fixed the localisation of the GUI even though the thesaurus is still set to English. And could you check also the luatex functionality?

**Comment by rugk** [comment]
Uhm this has permission problems if run without sudo and if it is run with sudo, I get some syntax error:
```
sudo flatpak --override --env=LC_ALL= org.texstudio.TeXstudio  
Fehler: 'org.texstudio.TeXstudio' is not a flatpak command. Did you mean 'create-usb'?

See 'flatpak --help'
```

**Comment by jakobjakobson13** [comment]
@rugk Can you execute the commands without the minuses before the override?

**Comment by rugk** [comment]
uups lol

Yeah thanks, works:
![texstudio-language](https://user-images.githubusercontent.com/11966684/68528165-5ed9e900-02ef-11ea-89a0-f07de585bb9b.png)

**Comment by jakobjakobson13** [comment]
And did luatex compile the document? If so, that leaves only the thesaurus to fix.

**Comment by rugk** [comment]
Yeah, I noticed no problem. :thinking:

**Comment by rugk** [comment]
Anyway, I guess having a localized GUI is already very nice, so you could fix this first issue first. :smile: 

And of course I cannot guarantee anything, better test the things by yourself. :wink:

**Comment by rugk** [comment]
Note: Languagetool also does not work yet, see #34

**Comment by rugk** [comment]
Maybe reopen this, as the thesaurus thing is not fixed yet according to the PR description?

**Comment by jakobjakobson13** [comment]
> Maybe reopen this, as the thesaurus thing is not fixed yet according to the PR description?

Have you tested the latest version? We should check it before we reopen this issue.

**Comment by rugk** [comment]
No, but that's what the PR says so… :ups

**Comment by jakobjakobson13** [comment]
The language tool seems to work fine on my PC with the most recent version.
```
         Kennung: org.texstudio.TeXstudio
             Ref: app/org.texstudio.TeXstudio/x86_64/stable
     Architektur: x86_64
           Zweig: stable
         Version: 3.0.1
         License: GPL-2.0
        Ursprung: flathub
      Collection: org.flathub.Stable
    Installation: user
       Installed: 4,1 GB
Laufzeitumgebung: org.kde.Platform/x86_64/5.15
             Sdk: org.kde.Sdk/x86_64/5.15

          Commit: 2cfe2168587c13b1d237188a1c9332b5f6250e92342a07f6ecc79ec321ba6…
          Parent: b073d4c646c229105ed4dd269f8476cff8c3c566d4b817ca68386b5818e41…
         Subject: Update to version 3.0.4 (6c6f4016)
            Date: 2021-01-22 23:46:43 +0000
```
But could you test it as well?

**Comment by rugk** [comment]
It works, but uses the wrong localisation.
This is German text and all settings set to German, but it suggests me English synonyms:
![grafik](https://user-images.githubusercontent.com/11966684/105615233-50ca9800-5dcf-11eb-8866-13d118db00aa.png)

**Comment by Alexander-Wilms** [comment]
I looked at the code and it seems like thesaurus_database is initialized [here](https://github.com/texstudio-org/texstudio/blob/75bced3df8724fa340a021902f3353a0823ce7ea/src/configmanager.cpp#L486) and then set to a specific file path [here](https://github.com/texstudio-org/texstudio/blob/75bced3df8724fa340a021902f3353a0823ce7ea/src/configmanager.cpp#L899).

I'll add some debug output and see if I can find the cause for this problem.

**Comment by Alexander-Wilms** [comment]
Hm, I added debug output, but can't reproduce the issue.

Can you delete ~/.var/app/org.texstudio.TeXstudio and try again?

**Comment by rugk** [comment]
> Can you delete ~/.var/app/org.texstudio.TeXstudio and try again?

Indeed, it works then.
Still strange though. It should also work without the need to delete the old app data.

I still have the old data. Is there anything I should/can provide you?

**Comment by Alexander-Wilms** [comment]
As I understand the code, it's working as intended. If you installed the Flatpak when it still contained the environment variable LC_ALL=C, TeXstudio set the thesaurus_database variable to the path of the English thesaurus. It just doesn't automatically change the path when the locale changes.
