### ISSUE TITLE
Do not use own binaries, use TexLive distribution

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#33]
> The org.freedesktop.Sdk.Extension.texlive got updated but org.texstudio.TeXstudio uses its own binary that has probably (that's my guess, at least) been copied from the org.freedesktop.Sdk.Extension.texlive earlier. And so an update of org.freedesktop.Sdk.Extension.texlive does not show any effect on the the binaries that are used by org.texstudio.TeXstudio

```
$ /var/lib/flatpak/runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/18.08/13b1f85825d4fd40fd90b59bf680ac90a47d1b04f9d1c042e7daa74cc4a5a052/files/bin/x86_64-linux/pdflatex TexLiveSdkTest.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)


$ /var/lib/flatpak/app/org.texstudio.TeXstudio/x86_64/stable/5bbbc114485cb314b75f14eb3deea3b16448b782ab4350e0a250e14a6852f07b/files/bin/x86_64-linux/pdflatex TexLiveSdkTest.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
```

---

The report and underlying problem is from https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/9#issuecomment-545864824

**Comment by jakobjakobson13** [comment]
Perhaps, an easy, but not really practical, workaround is to uninstall and reinstall the texstudio package.

**Comment by rugk** [comment]
Reinstalled, still `This is LuaTeX, Version 1.07.0 (TeX Live 2018)  (format=lualatex 2019.2.20)  28 OCT 2019 09:13`

**Comment by jakobjakobson13** [comment]
> Reinstalled, still `This is LuaTeX, Version 1.07.0 (TeX Live 2018) (format=lualatex 2019.2.20) 28 OCT 2019 09:13`

Then I was wrong. I thought the binaries would be copied during the local installation but apparently this is done when the flatpak package is build here at github. So I guess we have to wait for a rebuild.

**Comment by jakobjakobson13** [comment]
@rugk Can you check with your installation if this bug report still applies? If not, we could close it now.

**Comment by rugk** [comment]
Thanks. Works now:
> This is LuaTeX, Version 1.07.0 (TeX Live 2018)  (format=lualatex 2019.2.20)  9 NOV 2019 10:29
