### ISSUE TITLE
LanguageTool sometimes does not start

### ISSUE THREAD

**Issue by xuiqzy** [flathub/org.texstudio.TeXstudio#34]
Sometimes LanguageTool is available and started automatically and sometimes not.
Linux Distro: Arch Linux rolling latest
Output of `flatpak info org.texstudio.TeXstudio`
```
TeXstudio - LaTeX editor

          ID: org.texstudio.TeXstudio
         Ref: app/org.texstudio.TeXstudio/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.12.16
     License: GPL-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 3.7 GB
     Runtime: org.kde.Platform/x86_64/5.12
         Sdk: org.kde.Sdk/x86_64/5.12

      Commit: 5bbbc114485cb314b75f14eb3deea3b16448b782ab4350e0a250e14a6852f07b
      Parent: b8d64fb3dd6cb6af8d4761fa0adf7e2802de3eb24ba3421c49e9663577352cfa
     Subject: Add LanguageTool module (ffaf1a13)
        Date: 2019-08-26 13:56:26 +0000
```

Output of the `Check Languagtool` option under `Help` in TeXstudio:
```
which java: /app/jre/bin/java

JAVA: java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11)
OpenJDK 64-Bit Server VM (build 11.0.4+11, mixed mode)

Real-time checking is enabled.
Grammar checking is enabled.

Tries to start automatically.

LT current status: error

LT-URL: http://localhost:8081/v2/check

```
If I install Texstudio and LanguageTool without flatpak, the autostart never works, but starting LanguageTool manually works everytime.

I don't know how to debug this further to provide more info, any hints are appreciated!

**Comment by xuiqzy** [comment]
Setting `LT Path` to `/app/languagetool` in the Settings under `Language Checking` fixes this and correctly uses the builtin java and LanguageTool to start the server.

This should be integrated into this flatpak build of TexStudio to properly fix the default config, which already sets the `Start LanguageTool if not running` setting to true, but does not work without this fix.

Where would I set the default config for this  so I can make a pull request?

**Comment by rugk** [comment]
Can reproduce this.
At leats the path is definitively wrong.

Also autostarting does not work for me.

Note that you do not have to modify the dictionary path in the TexStudio settings.

But even if all that is set and I got a "LT is running" message, the "spell checking" menu entry in "tools" is not working and tells me it cannot find a dictionary. (In the setings the de_DE version is selected… :thinking: )

**Comment by Alexander-Wilms** [comment]
I think the issue is that TeXstudio doesn't remember changes to the settings

**Comment by Alexander-Wilms** [comment]
It seems to work reliably for me now that we use the host's java and languagetool.jar. Can you confirm this?

**Comment by rugk** [comment]
Given that this is problematic again (see https://github.com/flathub/org.texstudio.TeXstudio/issues/55), is there also a fallback for languagetool, as that is again a thing that may not (or rather is likely not to) be installed on the host?

**Comment by Alexander-Wilms** [comment]
Is installing java on Fedora Silverblue as problematic as TeX Live?

**Comment by rugk** [comment]
I have not tried yet, overlaying may be possible, but overlaying is always only considered a workaround. That's what we have flatpaks for…

Maybe we could have another extension for languagetool? Would that work?

**Comment by Alexander-Wilms** [comment]
Yes, that should work.

**Comment by rugk** [comment]
I'm the wrong one to ask, sorry.
