### ISSUE TITLE
poppler, konsole, LanguageTool and KDE Application Platform are outdated

### ISSUE THREAD

**Issue by xuiqzy** [flathub/org.texstudio.TeXstudio#35]
There are new releases available for `poppler`, `konsole` and `LanguageTool`.
There is also a new release of `KDE Application Platform`, but it seems like the older version still gets updates, so that is less important.

Can they just be upgraded with the newer versions? If that's okay I would change it, roughly test it and make a pull request.

Maybe we can set up some system to watch for new releases to then integrate them here?
Should I open a new issue for that?

**Comment by jakobjakobson13** [comment]
> There are new releases available for `poppler`, `konsole` and `LanguageTool`.
> There is also a new release of `KDE Application Platform`, but it seems like the older version still gets updates, so that is less important.
> 
> Can they just be upgraded with the newer versions? If that's okay I would change it, roughly test it and make a pull request.

In principle they should be upgradable without any problems. So you are welcome to create a pull request.

> Maybe we can set up some system to watch for new releases to then integrate them here?
> Should I open a new issue for that?

There are internet pages for that, but I don't know how automated this can be done. And if it is really desired to automate such things as sometimes upgrades can break the system badly. But for that you have ask someone else (and probably at some other place).

**Comment by xuiqzy** [comment]
Okay, thanks for the quick answer!
I'm on it. I had to explicitly install the 18.08 and not 19.08 versions of `texlive` and `openjdk11` to successfully build it, is that intended and how can one know the version needed of those since I can't see them in the yaml manifest?

Also, is it necessary to specify `openjdk11` or could we just use the latest `openjdk`?
Is this just a build or also a runtime dependency?

I meant only an automated notification or pull request or issue something like e.g. [Dependabot](https://dependabot.com/) to help realize when updates are available.

**Comment by xuiqzy** [comment]
I opened #36 for this:
https://github.com/flathub/org.texstudio.TeXstudio/pull/36

**Comment by Alexander-Wilms** [comment]
Fixed in d3217c2fb4158e0daa42d83fa6f9679c15964a31
