### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Queuecumber** [flathub/org.texstudio.TeXstudio#39]
I've tried about 5 times now to install this from flathub and I get a 503 error each time, I think because of the large size of the package. It fails randomly during the download. I doubt this is your bug but do you have any suggestions that might help me get it installed?

**Comment by willsALMANJ** [comment]
This is the same issue as #16. It would be nice if the flatpak could be broken up into a few components (maybe separate into texlive, latex, and tex packages?) that were smaller. I still have never successfully downloaded the flatpak.

**Comment by TheOneandOnlyJakfrost** [comment]
I was able to get it to install as a flatpak, but only after layering it onto my OS, so installing from the normal RPM. I run Fedora Silverblue, I had to layer the normal Fedora Workstation package for TeXstudio, which wouldn't run 100% (preview didn't work). After I had layered the package, the flatpak would install flawlessly, although slowly.

**Comment by Alexander-Wilms** [comment]
Looks like this issue is fixed now: https://github.com/flathub/flathub/issues/845
