### ISSUE TITLE
Problems with the \input and \include commands

### ISSUE THREAD

**Issue by JakobJakobson** [flathub/org.texstudio.TeXstudio#4]
Hi there (Alexander-Wilms)

I'm using 
```
Flatpak version: 0.8.8
Texstudio info: app/org.texstudio.TeXstudio/x86_64/stable flathub 97826ed0406886b0d2a180ddc802957fc704f69efe53d323f344384b995faca6
```

and the following three documents

Case A:
```tex
\documentclass{scrreprt}
\begin{document}
\include{content}
\end{document}
```

Case B:
```tex
\documentclass{scrreprt}
\begin{document}
\input{content}
\end{document}
```

content.tex
```tex
Content
```

The ```content.tex``` file is in the same directory as my main documents.
Case A pdflatex gives me a warning saying ```No file content``` and compiles the document without the content of the ```content.tex``` file , whereas case B gives me an error saying ```No file content and does not compile the document.

Also in the structure panel I can't open the ```content.tex``` file and it is marked red (as missing). If I click on it it a dialog saying ```The file "content.tex" does not exist. Do you want to create it``` even though it definitely exists.

Is this due to my old flatpak version or can you reproduce the issue?

Regards

**Comment by Alexander-Wilms** [comment]
If you enable the setting that shows the file path in the window title, is that the real path or /run/user/...?

You can try opening both, the main document and the included file (there's also a setting the does this autumatically).

**Comment by JakobJakobson** [comment]
The path is ```/run/user/...``` .

The automatical setting as well as the right clock option ```Open all related documents``` does not work either.

**Comment by Alexander-Wilms** [comment]
I had this issue when I initially submitted TeXstudio to flathub, but it seemed to be resolved. Maybe you need a newer version of xdg-desktop-portal-kde, containing the commits I linked to in the PR.

**Comment by JakobJakobson** [comment]
The bugs depending on the flatpak version. With flatpak version ```0.11.7``` the commands ```\input``` and ```\include``` work, whereas with flatpak version ```0.8.8``` it fails. (What is a shame because my PC at work uses CentOS with flatpak ```0.8.8``` where I would need the flawless flatpak version of texstudio much more urgent.)
So I'll close the issue.

**Comment by amtlib-dot-dll** [comment]
Similar issue still exists in `flatpak-0.99.2-1.fc28.x86_64`, as `\bibliography{personal}` cannot find `personal.bib` located under the same directory

**Comment by Alexander-Wilms** [comment]
Does TeXstudio show a /run/user/... path in the title bar as well?

**Comment by amtlib-dot-dll** [comment]
@Alexander-Wilms Thanks, it is under an external directory, and your code works

**Comment by Alexander-Wilms** [comment]
I've pushed a fix.
