### ISSUE TITLE
Update to newer version

### ISSUE THREAD

**Issue by username72764274** [flathub/org.texstudio.TeXstudio#42]
The TeXstudio flatpak is on version 2.12.16, while the current version is 2.12.22. Are there any plans for updating the flatpak version?

**Comment by rugk** [comment]
Worst thing is by default it checks for updates and annoys you with pretty useless "please upgrade me" commands (for a flatpak they are definitively useless, at least).

**Comment by Alexander-Wilms** [comment]
Fixed in d3217c2fb4158e0daa42d83fa6f9679c15964a31
