### ISSUE TITLE
Can we make use of the tex documentations?

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#45]
Can we somehow expose `texdoc` or so, so we can access the tex documentation?

I feel this is an important feature… :thinking: 

Also TexStudio's feature right-click -> "open package documentation for XY" does not work.

I guess this does not include the docs? :thinking:

**Comment by jakobjakobson13** [comment]
> Can we somehow expose `texdoc` or so, so we can access the tex documentation?
> 
> I feel this is an important feature… thinking
> 
> Also TexStudio's feature right-click -> "open package documentation for XY" does not work.
> 
> I guess this does not include the docs? thinking

We can include the docs into the texlive package, it's just a matter of the package size.

**Comment by rugk** [comment]
Hmm yeah, maybe optional, but I see optional things don't exist on Flathub? Okay, AFAIK flatpak has the concept of "add-ons" (that are checkboxes in GNOME Software)? Maybe you can make use of that?

**Comment by jakobjakobson13** [comment]
Currently I don't have the time for this. When I got more spare time, I'll try to get back to it.

**Comment by cjao** [comment]
I work around this by pointing texstudio to an existing texlive installation on my host system which I installed directly from the texlive website.  I think instead of packing more and more into the texstudio download, we should improve texstudio's ability to detect systemwide LaTeX installations and split off the bundled LaTeX into a plugin. This would have two advantages: 1) texlive on the host can be customized after installation and shared by other programs. 2) The initial download size for texstudio would decrease dramatically.

**Comment by jakobjakobson13** [comment]
> I think instead of packing more and more into the texstudio download, we should improve texstudio's ability to detect systemwide LaTeX installations and split off the bundled LaTeX into a plugin. This would have two advantages: 1) texlive on the host can be customized after installation and shared by other programs. 2) The initial download size for texstudio would decrease dramatically.

I agree. To get the opinion of two active maintainers of tex editors on a similar topic I opened [https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/35](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/35) . (Unfortunately, texstudio seems pretty abandoned.) 
My proposal would be to provide all latex extensions as optional addons and additionally make them more granular. But that would require a reorganisation of the latex extension and an update of the manifests of the tex editors.
Additionally one would also have to write a proper documentation how to either use the system's latex files or flatpak's latex files.

**Comment by jakobjakobson13** [comment]
> Can we somehow expose `texdoc` or so, so we can access the tex documentation?
> 
> I feel this is an important feature… thinking
> 
> Also TexStudio's feature right-click -> "open package documentation for XY" does not work.
> 
> I guess this does not include the docs? thinking

Currently we are not packaging the docs, as it would further increase the installation size. If the program `texdoc` works is another question.

**Comment by jakobjakobson13** [comment]
> Hmm yeah, maybe optional, but I see optional things don't exist on Flathub? Okay, AFAIK flatpak has the concept of "add-ons"/extension packages (that are checkboxes in GNOME Software)? Maybe you can make use of that?

You could, but that needs a rewriting of the manifest files by the respective maintainers.

**Comment by cjao** [comment]
See #51 and #52.

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation, so you can just use the regular TeX documentation.
