### ISSUE TITLE
Can we add pygmentize?

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#46]
In order to be able to use _minted_ one needs [pygments](https://pygments.org/) (aka pygmentize) installed.

It would be great if you could add it to the flatpak, because otherwise one cannot compile projects that use minted with this here.

---

My proposal to TexLive has been ignored, so far: https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/25

**Comment by jakobjakobson13** [comment]
> My proposal to TexLive has been ignored, so far: [flathub/org.freedesktop.Sdk.Extension.texlive#25](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/25)

It has actually been included in the texlive package but texstudio needs to be rebuild so that the new texlive packages gets "incorporated" into texstudio.

**Comment by rugk** [comment]
Ah really? Don't see it anywhere…

**Comment by Alexander-Wilms** [comment]
This Flatpak now uses the host's TeX Live installation, so if you have pygements installed on the host, it should work.

**Comment by rugk** [comment]
> This Flatpak now uses the host's TeX Live installation

Hmm, how does that work? Don't really get that – should not/is not it sandboxed?

Also, what happens if you have no TexLive installed on the host…

**Comment by rugk** [comment]
Ah hmm, opened a new issue for that though, #55…

**Comment by jakobjakobson13** [comment]
> This Flatpak now uses the host's TeX Live installation, so if you have pygements installed on the host, it should work.

I think the issue is more complicated as you can see here: https://github.com/flathub/org.tug.texworks/issues/11

**Comment by Alexander-Wilms** [comment]
I have patched TeXstudio to run all LaTeX-related commands via `flatpak-spawn --host`, if I understand it correctly, this talks about a different approach, right?

**Comment by jakobjakobson13** [comment]
> I have patched TeXstudio to run all LaTeX-related commands via `flatpak-spawn --host`, if I understand it correctly, this talks about a different approach, right?

Yes, your approach is different from texworks' approach. You are using the host directly ( `flatpak-spawn --host` ) whereas texstudio tried to remap the binaries in the (now unused) patch. Your workaround looks good for the moment even though on a long term it is probably an issue to address.

**Comment by rugk** [comment]
Anyway let's better discuss is it in the issue, where it belongs to: https://github.com/flathub/org.texstudio.TeXstudio/issues/55
