### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#47]
I do see many open PRs where only the build bot ran and nothing else happened…

The [last commit](https://github.com/flathub/org.texstudio.TeXstudio/commit/13d989928f182ec45798c108c5e1549c58b29bc7) is from 2019 and nobody reacts to issues.

**Comment by jurf** [comment]
Yeah, I think that speaks for itself. Feeling up to it? :grin:

**Comment by picsel2** [comment]
> Feeling up to it? grin

What does it take?

**Comment by jurf** [comment]
Maintaining a Flatpak is not hard. Once you grasp the [basics](https://docs.flatpak.org/en/latest/first-build.html), it just takes determination and experimentation to get everything to work right. Since this is already built, it only requires figuring out possible bugs caused by the upgrade.

**Comment by jakobjakobson13** [comment]
I could co-maintain, if you need a hand.

**Comment by picsel2** [comment]
Thanks for the offer! Unfortunately I have not the necessary spare time at the moment, but I'll come back to it probably at the end of this month.

**Comment by mbd98** [comment]
If you're still looking for a new maintainer, I'd be very happy to help out!

**Comment by cjao** [comment]
I use TeXstudio regularly and would also be happy to help. Is there a beta channel where we can test changes to the packaging?

**Comment by jurf** [comment]
Sure, every app can have a beta branch. You can also test changes in a PR, which gets built automatically.

**Comment by picsel2** [comment]
A little follow-up on https://github.com/flathub/org.texstudio.TeXstudio/issues/47#issuecomment-737053851.
I'm sorry but I won't have the time to take over a reliable maintainership and I don't think that this will change in the foreseeable future. 😔

**Comment by Alexander-Wilms** [comment]
It's now maintained again
