### ISSUE TITLE
Opening an external document viewer fails

### ISSUE THREAD

**Issue by JakobJakobson** [flathub/org.texstudio.TeXstudio#5]
Hi there (Alexander-Wilms)

I'm using 
```
Flatpak version: 0.8.8
Texstudio info: app/org.texstudio.TeXstudio/x86_64/stable flathub 97826ed0406886b0d2a180ddc802957fc704f69efe53d323f344384b995faca6
```

I can't open the external viewer via texstudio as I get the following error message:

```
Process started: xdg-open "scrreprt".pdf

Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Keine derartige Methode ?OpenFile?

Process exited with error(s)
```

Is this due to my old flatpak version or can you reproduce it?

Regards,

Jakob

**Comment by Alexander-Wilms** [comment]
I'm fairly certain that this worked for ne. I can try it tonight. Does this occur with other apps as well?

**Comment by JakobJakobson** [comment]
It's depending on the flatpak version. With flatpak version ```0.11.7``` you can open the external document viewer.
So I'll close the issue.
