### ISSUE TITLE
Update TexLive to 2020

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#53]
[The TexLIve flatpak package provides an up-to-date TexLive 2020 distribution](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/),  but you have not updated it yet. Could you please just rebuild it?

See:
> TexLive 2020 is provided in all branches, isn't it? However, the tex editors that bundle the texlive extension have to be rebuild manually for bundling the newest version of the texlive extension.

https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/pull/30#issuecomment-757354880

**Comment by Alexander-Wilms** [comment]
Package has been rebuilt
