### ISSUE TITLE
Flatpak spawn (usage of host's TexLive distro) may cause issues on certain distributions

### ISSUE THREAD

**Issue by rugk** [flathub/org.texstudio.TeXstudio#55]
Oh `flatpak spawn` is used to use the host's TeX Live installation. I wonder whether this is possible to use on Fedora Silverblue now given [installing TexLive on the host is there nearly impossible](https://discussion.fedoraproject.org/t/latex-on-silverblue-texconfig/765?u=rugk).

So does it/can it still fallback to the packaged Tex version?

I liked the "we include Tex(Live) in the flatpak" way better, also because it is how flatpak is supposed to be used. Breaking out of the sandbox is clearly not what one should do, usually (i.e. when it can be avoided). It obviously re-introduces the a system dependency on the host, which now here e.g. needs TexLive to be installed(?). This limits the cross-distro-comaptibility that flatpak aims to provide.

**Comment by jakobjakobson13** [comment]
A similar problem is described here https://github.com/flathub/org.tug.texworks/issues/11

**Comment by Alexander-Wilms** [comment]
The flatpak'd version of TeX Live has the disadvantage that one has no granular control over the packages, the TeXstudio build takes ages and is huge.

Having an optional TeX Live extension would be nice, as mentioned in https://github.com/flathub/org.texstudio.TeXstudio/pull/51

I have no experience with extensions, though. Do you know if this would be opt-in or opt-out and if the changes in the linked PR is all that's required for this to work?

**Comment by rugk** [comment]
Let's better ask @cjao. And yeah, if it is optional, then I could see one could use this as a "fallback". This would be the best solution IMHO.

**Comment by Alexander-Wilms** [comment]
I've added a patch detecting the TeX Live extension: https://github.com/flathub/org.texstudio.TeXstudio/pull/51

During testing it seems to work fine. If you install or remove the TeX Live extension, you'll might need to remove the luaotfload cache (I just deleted the ~/.var/org.texstudio.TeXstudio directory)

I'm not sure if the old finish-args are even needed anymore:
```
  - --env=TMPDIR=/var/tmp # for lockfiles
  - --env=TEXMFCACHE=$XDG_CACHE_HOME
  - --env=TEXINPUTS=.:~/texmf/:
```

**Comment by State-Of-Joshing-Gentle-Peevishness** [comment]
You should at least mention somewhere on flathub, that this flatpak version of texstudio cannot run alone and that an installation of tex-live is needed. Just removing tex-live caused my texstudio version to not compile anymore from one day to the other. Probably my own fault as my system updates flatpaks silently ;-)

**Comment by achimfrase** [comment]
Hey,

this is also a problem for me.
Suddenly TeXstudio doen't work any more.

I wrote an bug-report at the wrong project.
[https://github.com/texstudio-org/texstudio/issues/1469](url)

I hope this problem gets fixed really soon.

Thanks in Advance
Achim

**Comment by State-Of-Joshing-Gentle-Peevishness** [comment]
Flatpak-texstudio didn't warn me that suddenly tex-live is missing. When I installed tex-live from my distributions repository it wasn't found. Before tinkering too long I abandoned the flatpak version and installed the latest from texstudio.org. The benefit of the flatpak version that everything worked out of the box is now lapsed.

**Comment by Alexander-Wilms** [comment]
@achimfrase Can you test if this works: https://github.com/flathub/org.texstudio.TeXstudio/pull/51

With this change, one can optionally install TeX Live as a flatpak:

```
flatpak install --user https://dl.flathub.org/build-repo/37784/org.texstudio.TeXstudio.flatpakref
flatpak install flathub org.freedesktop.Sdk.Extension.texlive//20.08
flatpak run org.texstudio.TeXstudio//test
```

**Comment by achimfrase** [comment]
> @achimfrase It should work again if you install the TeX Live extension:
> 
> ```
> flatpak install flathub org.freedesktop.Sdk.Extension.texlive//20.08
> ```

I am sorry, but it is not working. I installed the TeX Live extention but TeXstudio doesn't find pdflatex.
Any hints for me?

**Comment by achimfrase** [comment]
Thank you for your support.
Now it works again. :-)

Am Montag, dem 15.02.2021 um 11:31 -0800 schrieb Alexander Wilms:

**Comment by rugk** [comment]
Ah thanks for adding an explanation, see https://github.com/flathub/org.texstudio.TeXstudio/commit/f275209caa1efa8b88c8b187addca78fd8a6b92e. Seems this is really needed. :smiley:

**Comment by rugk** [comment]
There is still one disadvantage though for the TexLive Extension way: You still have this "breakout of sandbox" permission. That is then not necessary anymore at all.

But you could likely override to remove that again when  using, could not you?

**Comment by Alexander-Wilms** [comment]
Yes, if you add the arguments `--nofilesystem=host --nofilesystem=/tmp --disallow=devel --socket=session-bus` to `flatpak run`
