### ISSUE TITLE
Add note explaining how the texlive extension works

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/org.texstudio.TeXstudio#59]
As previously mentioned #55 an explanation of the new texlive extension mechanism would be very useful. The only question is where to put that explanation/message:
* In the `readme` file of the flathub repository.
     -  Pro: Easiest fix as only one file needs to be created.
     - Con: `flathub.org` won't show the message.
    - Con: Users using their distro-provided software manager won't get the message.
    - Con: In my oppinion, you can't expect an average user to check the flathub repository.
* In the appdata file (English section) via a patch on flathub
    - Pro: `flathub.org` will show the explanation.
    - Pro: English users using their distro-provided software manager will get the message.
    - Second easiest fix
    - Con: Non-English users using their distro-provided software manager won't get the message.
* In the appdata file (English section and every translation) via a patch on flathub
   - Pro: `flathub.org` will show the message.
   - Pro: English and Non-English users using their distro-provided software manager will get the message.
   - Con: Least easiest fix
   - Con: A lot of work that will (probably) never get upstreamed as the distribution via flatpak is still quite exotic.
   - Con: A change in the upstream appdata file could require a fixed patch.

What's your preferred option @Alexander-Wilms ?

**Comment by Alexander-Wilms** [comment]
I'd choose the second option for now.

What do you think of this disclaimer?

> Requires either TeX Live being installed on the system from your distribution's repositories or the TeX Live Flatpak, which you can install by running 'flatpak install flathub org.freedesktop.Sdk.Extension.texlive//20.08'

**Comment by jakobjakobson13** [comment]
Sounds fine to me.
