### ISSUE TITLE
IBus IME failed to work, CJK characters cannot be typed in

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.texstudio.TeXstudio#6]
```shell
$ grep PRETTY_NAME /etc/os-release 
PRETTY_NAME="Fedora 28 (Twenty Eight)"
$ rpm -q ibus flatpak
ibus-1.5.18-5.fc28.x86_64
flatpak-0.99.2-1.fc28.x86_64
```

The IME seems to be inactive even when switched on, just like these issues https://github.com/search?q=org%3Aflathub+ibus&type=Issues. It fails even with these overrides: `$ flatpak run --env=XMODIFIERS=@im=ibus --env=GTK_IM_MODULE=ibus --env=QT_IM_MODULE=ibus --talk-name=org.freedesktop.IBus org.texstudio.TeXstudio`

**Comment by RoyiAvital** [comment]
When will you update to the latest TeXStudio (2.12.10)?

**Comment by amtlib-dot-dll** [comment]
@RoyiAvital Sorry but I am not responsible for the update of this application

**Comment by Alexander-Wilms** [comment]
I've updated TeXstudio to 2.12.10.

Does the issue also occur with other Qt applications?

**Comment by amtlib-dot-dll** [comment]
However https://github.com/KDE/flatpak-kde-runtime does not allow issuing? :thinking:

**Comment by Alexander-Wilms** [comment]
@aleixpol Where could the issue be reported? I didn't see any category in the KDE Bugzilla that would fit.

**Comment by aleixpol** [comment]
I guess we need to see where the bug is really. I looked it up and the ibus plugin is already present in `/usr/lib/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so`.

@amtlib-dot-dll if you could shed some light I'll be happy to apply the fix in the runtime.

**Comment by Alexander-Wilms** [comment]
@amtlib-dot-dll Does this issue still occur? If yes, do you have any more information?

**Comment by amtlib-dot-dll** [comment]
@Alexander-Wilms Yes, Chinese characters still cannot be typed in. Nothing had changed since. :man_shrugging:

**Comment by kenya888** [comment]
Hi,

I have the same issue with flatpak Telegram App.
I think ibus uses another d-bus interface in flatpak environment that describes below.

https://github.com/ibus/ibus/commit/35ce62474fa97a5460d72c360943700a413a07ae

we may have to create patch libibusplatforminputcontextplugin.so to use ibus-portal d-bus interface.

**Comment by kenya888** [comment]
Sorry, It's mislead. qt ibus plugin is already use ibus portal if it is in flatpak...

**Comment by Alexander-Wilms** [comment]
I updated the runtime to 5.11. Any changes?

**Comment by aleixpol** [comment]
@alexlarsson would you happen to know what's wrong?

**Comment by kenya888** [comment]
@Alexander-Wilms works fine to me. Thanks!!

This change makes good in Qt 5.11.2.
https://codereview.qt-project.org/#/c/236421/

**Comment by Alexander-Wilms** [comment]
Great!
