### ISSUE TITLE
Suggestion: add $HOME/texmf to TeXlive search paths

### ISSUE THREAD

**Issue by cjao** [flathub/org.texstudio.TeXstudio#7]
User-installed packages and stylesheets are normally placed in $HOME/texmf. However, TeXstudio cannot compile documents using said packages and stylesheets since the bundled installation of Texlive does not search that search that directory. A possible fix would be to add ~/texmf to the TEXINPUTS environment variable, which is read by kpathsea.

**Comment by Alexander-Wilms** [comment]
Should be fixed now
