### ISSUE TITLE
Flatpak not using host packages

### ISSUE THREAD

**Issue by LyzardKing** [flathub/org.texstudio.TeXstudio#98]
Hi. I installed the flatpak without the texlive package (with the --no-related cli flag)
When I start the program though, I cannot run any command, as they are not seen by the flatpak.
In the options window the command paths are all set to `<unknown>`

If I sh in the flatpak I can succesfully run `flatpak-spawn --host <command>`
Is there some configuration missing in the flatpak available now on flathub?

Thanks

**Comment by Alexander-Wilms** [comment]
I think the step of setting up these commands failed when first opening the settings page. Does it work if you set the commands manually?

**Comment by LyzardKing** [comment]
I tried to add the commands manually, with the `flatpak-spawn --host` part, but that didn't work.
I tried adding the texlive flatpak, so it picked up the proper commands, then I removed it, and the commands were automatically set, without that part, and working.
I guess the issue is what you said. There should probably be a default set of commands, even if they fail at first.

**Comment by LyzardKing** [comment]
While it works with the commands set manually, it forces a download of the texlive extension.
Is it possible to avoid that? I can install texstudio without the extension, but when I run an update it is downloaded as well.

**Comment by renanwp2** [comment]
I can't use svg Latex package, but I have it installed in my host machine.

**Comment by Alexander-Wilms** [comment]
The example given in the svg [documentation](https://www.ctan.org/pkg/svg) works for me when I add `flatpak-spawn --host` to the (Lua)LaTeX command:
![grafik](https://user-images.githubusercontent.com/3226457/219053507-94a6fd2f-0b77-4f6b-930f-37e64debd6f6.png)

```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{svg}
\usepackage[off]{svg-extract}
\svgsetup{clean=true}
%\pdfsuppresswarningpagegroup=1
\usepackage{relsize}
\usepackage{subcaption}
\begin{document}
	\begin{figure}
		\begin{minipage}{\dimexpr\linewidth/2\relax}
			\includesvg[width=\linewidth]{svg-example}%
			\subcaption{This text is too large!}%
		\end{minipage}%
		\begin{minipage}{\dimexpr\linewidth/2\relax}
			\includesvg[width=\linewidth,pretex=\relscale{0.6}]{svg-example}%
			\subcaption{This text fits better.}%
		\end{minipage}
		\caption{An example figure with \LaTeX~support\label{fig:example}}%
	\end{figure}
	\begin{figure}\centering
		\includesvg[%
		width=.5\linewidth,inkscapelatex=false,extractformat={pdf,eps}%
		]{svg-example}%
		\caption{The same example figure without \LaTeX~support}%
	\end{figure}
\end{document}
```
